// OPERATIONS
export const FETCH_OPERATIONS_START = 'FETCH_OPERATIONS_START'
export const FETCH_OPERATIONS_SUCCESS = 'FETCH_OPERATIONS_SUCCESS'
export const FETCH_OPERATIONS_ERROR = 'FETCH_OPERATIONS_ERROR'

export const FETCH_OPERATION_START = 'FETCH_OPERATION_START'
export const FETCH_OPERATION_SUCCESS = 'FETCH_OPERATION_SUCCESS'
export const FETCH_OPERATION_ERROR = 'FETCH_OPERATION_ERROR'

export const CREATE_OPERATION_START = 'CREATE_OPERATION_START'
export const CREATE_OPERATION_SUCCESS = 'CREATE_OPERATION_SUCCESS'
export const CREATE_OPERATION_ERROR = 'CREATE_OPERATION_ERROR'

export const FETCH_OPERATION_PRODUCTS = 'FETCH_OPERATION_PRODUCTS'

// ORDERS
export const FETCH_ORDERS_START = 'FETCH_ORDERS_START'
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS'
export const FETCH_ORDERS_ERROR = 'FETCH_ORDERS_ERROR'

export const FETCH_ORDER_START = 'FETCH_ORDER_START'
export const FETCH_ORDER_SUCCESS = 'FETCH_ORDER_SUCCESS'
export const FETCH_ORDER_ERROR = 'FETCH_ORDER_ERROR'

export const CREATE_ORDER_START = 'CREATE_ORDER_START'
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS'
export const CREATE_ORDER_ERROR = 'CREATE_ORDER_ERROR'

// PRODUCTS
export const FETCH_PRODUCTS_START = 'FETCH_PRODUCTS_START'
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS'
export const FETCH_PRODUCTS_ERROR = 'FETCH_PRODUCTS_ERROR'

export const FETCH_PRODUCT_START = 'FETCH_PRODUCT_START'
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS'
export const FETCH_PRODUCT_ERROR = 'FETCH_PRODUCT_ERROR'

export const CREATE_PRODUCT_START = 'CREATE_PRODUCT_START'
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS'
export const CREATE_PRODUCT_ERROR = 'CREATE_PRODUCT_ERROR'

export const UPDATE_PRODUCT_START = 'CREATE_PRODUCT_START'
export const UPDATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS'
export const UPDATE_PRODUCT_ERROR = 'CREATE_PRODUCT_ERROR'

export const FETCH_PRODUCT_PRICE = 'FETCH_PRODUCT_PRICE'

// PROVIDERS
export const FETCH_PROVIDERS_START = 'FETCH_PROVIDERS_START'
export const FETCH_PROVIDERS_SUCCESS = 'FETCH_PROVIDERS_SUCCESS'
export const FETCH_PROVIDERS_ERROR = 'FETCH_PROVIDERS_ERROR'

export const FETCH_PROVIDER_START = 'FETCH_PROVIDER_START'
export const FETCH_PROVIDER_SUCCESS = 'FETCH_PROVIDER_SUCCESS'
export const FETCH_PROVIDER_ERROR = 'FETCH_PROVIDER_ERROR'

export const CREATE_PROVIDER_START = 'CREATE_PROVIDER_START'
export const CREATE_PROVIDER_SUCCESS = 'CREATE_PROVIDER_SUCCESS'
export const CREATE_PROVIDER_ERROR = 'CREATE_PROVIDER_ERROR'

// CONTAINERS
export const FETCH_CONTAINERS_START = 'FETCH_CONTAINERS_START'
export const FETCH_CONTAINERS_SUCCESS = 'FETCH_CONTAINERS_SUCCESS'
export const FETCH_CONTAINERS_ERROR = 'FETCH_CONTAINERS_ERROR'

export const FETCH_CONTAINER_START = 'FETCH_CONTAINER_START'
export const FETCH_CONTAINER_SUCCESS = 'FETCH_CONTAINER_SUCCESS'
export const FETCH_CONTAINER_ERROR = 'FETCH_CONTAINER_ERROR'

export const CREATE_CONTAINER_START = 'CREATE_CONTAINER_START'
export const CREATE_CONTAINER_SUCCESS = 'CREATE_CONTAINER_SUCCESS'
export const CREATE_CONTAINER_ERROR = 'CREATE_CONTAINER_ERROR'

// CATALOGS
export const FETCH_CATALOGS_START = 'FETCH_CATALOGS_START'
export const FETCH_CATALOGS_SUCCESS = 'FETCH_CATALOGS_SUCCESS'
export const FETCH_CATALOGS_ERROR = 'FETCH_CATALOGS_ERROR'

export const FETCH_CATALOG_START = 'FETCH_CATALOG_START'
export const FETCH_CATALOG_SUCCESS = 'FETCH_CATALOG_SUCCESS'
export const FETCH_CATALOG_ERROR = 'FETCH_CATALOG_ERROR'

export const CREATE_CATALOG_START = 'CREATE_CATALOG_START'
export const CREATE_CATALOG_SUCCESS = 'CREATE_CATALOG_SUCCESS'
export const CREATE_CATALOG_ERROR = 'CREATE_CATALOG_ERROR'

// COUNTRIES
export const FETCH_COUNTRIES_START = 'FETCH_COUNTRIES_START'
export const FETCH_COUNTRIES_SUCCESS = 'FETCH_COUNTRIES_SUCCESS'
export const FETCH_COUNTRIES_ERROR = 'FETCH_COUNTRIES_ERROR'

export const FETCH_COUNTRY_START = 'FETCH_COUNTRY_START'
export const FETCH_COUNTRY_SUCCESS = 'FETCH_COUNTRY_SUCCESS'
export const FETCH_COUNTRY_ERROR = 'FETCH_COUNTRY_ERROR'

export const CREATE_COUNTRY_START = 'CREATE_COUNTRY_START'
export const CREATE_COUNTRY_SUCCESS = 'CREATE_COUNTRY_SUCCESS'
export const CREATE_COUNTRY_ERROR = 'CREATE_COUNTRY_ERROR'
