// IMPORTERS
export const FETCH_IMPORTERS_START = 'FETCH_IMPORTERS_START'
export const FETCH_IMPORTERS_SUCCESS = 'FETCH_IMPORTERS_SUCCESS'
export const FETCH_IMPORTERS_ERROR = 'FETCH_IMPORTERS_ERROR'

export const FETCH_IMPORTER_START = 'FETCH_IMPORTER_START'
export const FETCH_IMPORTER_SUCCESS = 'FETCH_IMPORTER_SUCCESS'
export const FETCH_IMPORTER_ERROR = 'FETCH_IMPORTER_ERROR'

// PRODUCTS
export const FETCH_PRODUCTS_START = 'FETCH_PRODUCTS_START'
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS'
export const FETCH_PRODUCTS_ERROR = 'FETCH_PRODUCTS_ERROR'

export const FETCH_PRODUCT_START = 'FETCH_PRODUCTS_START'
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCTS_SUCCESS'
export const FETCH_PRODUCT_ERROR = 'FETCH_PRODUCTS_ERROR'

// PROVIDERS
export const FETCH_PROVIDERS_START = 'FETCH_PROVIDERS_START'
export const FETCH_PROVIDERS_SUCCESS = 'FETCH_PROVIDERS_SUCCESS'
export const FETCH_PROVIDERS_ERROR = 'FETCH_PROVIDERS_ERROR'

export const FETCH_PROVIDER_START = 'FETCH_PROVIDER_START'
export const FETCH_PROVIDER_SUCCESS = 'FETCH_PROVIDER_SUCCESS'
export const FETCH_PROVIDER_ERROR = 'FETCH_PROVIDER_ERROR'

