export const FETCH_IMPORTERS_START = 'FETCH_IMPORTERS_START'
export const FETCH_IMPORTERS_SUCCESS = 'FETCH_IMPORTERS_SUCCESS'
export const FETCH_IMPORTERS_ERROR = 'FETCH_IMPORTERS_ERROR'

export const FETCH_IMPORTER_START = 'FETCH_IMPORTER_START'
export const FETCH_IMPORTER_SUCCESS = 'FETCH_IMPORTER_SUCCESS'
export const FETCH_IMPORTER_ERROR = 'FETCH_IMPORTER_ERROR'

