// IMPORTERS
export const FETCH_IMPORTERS_START = 'FETCH_IMPORTERS_START'
export const FETCH_IMPORTERS_SUCCESS = 'FETCH_IMPORTERS_SUCCESS'
export const FETCH_IMPORTERS_ERROR = 'FETCH_IMPORTERS_ERROR'

export const FETCH_IMPORTER_START = 'FETCH_IMPORTER_START'
export const FETCH_IMPORTER_SUCCESS = 'FETCH_IMPORTER_SUCCESS'
export const FETCH_IMPORTER_ERROR = 'FETCH_IMPORTER_ERROR'

// PRODUCTS
export const FETCH_PRODUCTS_START = 'FETCH_PRODUCTS_START'
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS'
export const FETCH_PRODUCTS_ERROR = 'FETCH_PRODUCTS_ERROR'

export const FETCH_PRODUCT_START = 'FETCH_PRODUCTS_START'
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCTS_SUCCESS'
export const FETCH_PRODUCT_ERROR = 'FETCH_PRODUCTS_ERROR'

// CONTAINERS
export const FETCH_CONTAINERS_START = 'FETCH_CONTAINERS_START'
export const FETCH_CONTAINERS_SUCCESS = 'FETCH_CONTAINERS_SUCCESS'
export const FETCH_CONTAINERS_ERROR = 'FETCH_CONTAINERS_ERROR'

export const FETCH_CONTAINER_START = 'FETCH_CONTAINER_START'
export const FETCH_CONTAINER_SUCCESS = 'FETCH_CONTAINER_SUCCESS'
export const FETCH_CONTAINER_ERROR = 'FETCH_CONTAINER_ERROR'

